language: objective-c
osx_image: xcode9.0
xcode_project: Functional.xcodeproj
xcode_scheme: Functional
xcode_sdk: macosx10.13

script:
  - build
  - xcodebuild clean build test -project "Functional.xcodeproj" -scheme "Functional" -destination 'generic/platform=macOS'

after_success:
  - bash <(curl -s https://codecov.io/bash)
